name: Deploy Docker Image

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  push:
    tags:
      - v*
env:
  image_name: docker-scanner

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_REGISTRY }}

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_REGISTRY }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          tags: |
            ${{ secrets.DH_USER }}/${{ env.image_name }}:${{ github.ref }}
            ghcr.io/${{ github.repository_owner }}/${{ env.image_name }}:${{ github.ref }}
            ghcr.io/${{ github.repository_owner }}/${{ env.image_name }}:latest
